services:
  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  api:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongodb:27017/task_manager
    depends_on:
      - mongodb

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  mongo_data: